version: '3'

services:
  api-oath:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/api-oath
    container_name: api-oath
    ports:
      - 5050:5050
    volumes:
      - ./app/main.py:/code/app/main.py
    networks:
      default:
        aliases:
          - api-oath.local.com
  
  mysql:
    image: mysql:latest
    container_name: api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo_oath
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      default:
        aliases:
          - mysqldb.local.com
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend-oath
    command: npx serve
    ports:
      - "3000:3000"
    networks:
      default:
        aliases:
          - oath.frontend.local.com
    
